version: '3.8'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 